from db.postgres_store import close_pool, get_pool

with get_pool().connection() as connection:
    connection.execute("""
        CREATE TABLE IF NOT EXISTS people (
            id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name               TEXT NOT NULL UNIQUE,
            gender             TEXT,
            race               TEXT,
            birthday           TEXT,
            profession         TEXT,
            image_link         TEXT,
            photo_position_x   DOUBLE PRECISION DEFAULT 50,
            photo_position_y   DOUBLE PRECISION DEFAULT 50
        )
    """)

print("Initialized the 'people' table.")
close_pool()
